"""empty message

Revision ID: 3dec31fb22b0
Revises: None
Create Date: 2016-04-23 16:26:37.650204

"""

# revision identifiers, used by Alembic.
revision = '3dec31fb22b0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grammars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grammar', postgresql.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('use_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grammars')
    ### end Alembic commands ###
